name: WordPress Deploy/Destroy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run:  |
          cd terraform
          terraform apply -auto-approve -input=false
        working-directory: ./terraform
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run:  |
          cd terraform
          terraform destroy -auto-approve -input=false
        working-directory: ./terraform
        env:
          TF_VAR_db_password: "dummy_value"
